### PR TITLE
Cleaning up some code

### PR DESCRIPTION
**Pull request by JezzaR-The-Proto**
Also fixed linebreak issue with help

### CODE REVIEW

**Comment by JezzaR-The-Proto** [comment]
Ok so, what you have in Luna.py as the prefix isn't the prefix for the bot that you have running?

**Comment by JezzaR-The-Proto** [comment]
Nvm, looking into commands.py shows you have 1 main command (called yiff) and then a type afterwards. I would recommend splitting these into separate commands and changing the prefix to $yiff

**Comment by JezzaR-The-Proto** [comment]
The prefix is no longer $yiff, it is now just $. Help has been moved to a separate command ($help) and yiff is now its own command, which will allow you to add more commands that dont require the $yiff prefix

**Comment by SuperWaffleKitty** [comment]
I had already fixed many of the issues presented by the time I say your pull request and reformatted a lot of the code. Because of this, it would be difficult to try merging your repo.  You may want to pull the latest master to compare with what you had implemented just to double check.

**Pull request closed without merging**
